---
- name: Setup host
  hosts:
    - all
  become: true

  tasks:
    - name: Install BATCAT
      ansible.builtin.apt:
        name: bat
        state: present
        update_cache: true

    - name: Remove old packages
      ansible.builtin.apt:
        autoremove: true

    - name: Clear out APT cache
      ansible.builtin.apt:
        clean: true
